<?xml version="1.0" encoding="utf-8"?>
<Project>
 	<PropertyGroup>
		<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<Import Project="Sdk.props" Sdk="Arkarin0.DotNet.Arcade.Sdk" />
  <Import Project="eng\targets\Settings.props"/>

<PropertyGroup>
  <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">net472;net8.0</TargetFrameworks>
  <!-- Use the same language version for the desktop and .NET 8 builds. -->
  <LangVersion>12.0</LangVersion>
</PropertyGroup>
 
</Project>
