<Project>
  <PropertyGroup>
    <BaseOutputPath Condition="'$(BaseOutputPath)' == ''">bin/</BaseOutputPath>
    <OutputPath Condition="'$(OutputPath)' == ''">$(BaseOutputPath)$(Configuration)/</OutputPath>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == ''">obj/</BaseIntermediateOutputPath>
    <IntermediateOutputPath Condition="'$(IntermediateOutputPath)' == ''">$(BaseIntermediateOutputPath)$(Configuration)/</IntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(BaseOutputPath)/**;$(BaseIntermediateOutputPath)/**;$(OutputPath)/**;$(IntermediateOutputPath)/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
