using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Alarmlist.Compiler.XML
{
    /// <summary>
    /// This class represents a Cause/Solution pair for <see cref="AlarmData"/>.
    /// </summary>
    /// <autogeneratedoc />
    [XmlRoot(ElementName = "Solution")]
    public class XMLAlarmSolution
    {
        [XmlElement]
        public string Cause { get; set; }

        [XmlElement(ElementName = "Resolve", Type = typeof(string))]
        public List<string> Solutions { get; set; } = new List<string>();
    }
}
