using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Alarmlist.Compiler.XML
{
    /// <summary>
    /// This class represents is a collection of <see cref="XMLAlarmSolution"/>s.
    /// </summary>
    /// <autogeneratedoc />
    [XmlRoot(ElementName = "Solutions")]
    public class XMLSolutionList
    {
        [XmlElement(ElementName ="clear")]
        public string ClearContent { get; set; }

        public bool IsClearRequested => ClearContent != null;

        [XmlElement(ElementName = "Solution", Type = typeof(XMLAlarmSolution))]
        public List<XMLAlarmSolution> Items { get; set; } = new List<XMLAlarmSolution> ();
    }
}
