using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Alarmlist.Compiler
{
    /// <summary>
    /// This class represents a Cause/Resolve pair for a <see cref="AlarmData"/> item.
    /// </summary>
    public class AlarmSolution
    {
        /// <summary>
        /// Gets or sets adescription of the cause of the error.
        /// </summary>
        /// <autogeneratedoc />
        public string Cause { get;set;}

        /// <summary>
        /// Gets or sets a list of solutions for this <see cref="Cause"/>.
        /// </summary>
        /// <autogeneratedoc />
        public List<string> Solutions { get; set; } = new List<string>();
    }
}
