//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;

//namespace Alarmlist.Syntax
//{
//    /// <summary>
//    /// This class represents a Cause/Resolve pair for a <see cref="Alarm"/> item.
//    /// </summary>
//    public class AlarmSolution : IAlarmSolution
//    {
//        /// <summary>
//        /// Gets or sets adescription of the cause of the error.
//        /// </summary>
//        /// <autogeneratedoc />
//        public string Cause { get; set; }

//        /// <summary>
//        /// Gets or sets a list of solutions for this <see cref="Cause"/>.
//        /// </summary>
//        /// <autogeneratedoc />
//        public List<string> Solutions { get; } = [];
//    }
//}
