<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>AlarmList.MSBuild.UnitTests</RootNamespace>
    <IsUnitTestProject>true</IsUnitTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.8.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="15.7.179" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlarmList.MSBuild\AlarmList.MSBuild.csproj" />
  </ItemGroup>
</Project>
