// Created/modified by Arkarin0 under one ore more license(s).

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Alarmlist.Syntax;

namespace Alarmlist.Text
{
    public class SourceText
    {
        public SourceText()
        {
            Alarms = new ObservableCollection<AlarmSyntaxNode>();
        }

        public ObservableCollection<AlarmSyntaxNode> Alarms { get; protected set; }

        /// <summary>
        /// Reads this instance.
        /// </summary>
        /// <returns>AlarmSyntaxTree.</returns>
        /// <autogeneratedoc />
        public AlarmSyntaxTree Read()
        {
            this.BeforeRead();
            var result =this.OnRead();
            if (result != null)
                SetSyntaxTree(result);
            this.AfterRead(result);
            return result;
        }

        protected void SetSyntaxTree(AlarmSyntaxTree tree)
        {
            tree = tree ?? new AlarmSyntaxTree();
            Alarms = new ObservableCollection<AlarmSyntaxNode>(tree.Alarms);
        }

        /// <summary>
        /// Befores the read.
        /// </summary>
        /// <autogeneratedoc />
        protected virtual void BeforeRead() { }

        /// <summary>
        /// Afters the read.
        /// </summary>
        /// <autogeneratedoc />
        protected virtual void AfterRead(AlarmSyntaxTree tree) { }

        /// <summary>
        /// Called when [read].
        /// </summary>
        /// <returns>AlarmSyntaxTree.</returns>
        /// <autogeneratedoc />
        protected virtual AlarmSyntaxTree OnRead()
        {
            var tree = new AlarmSyntaxTree();
            foreach (var alarm in Alarms)
                tree.Alarms.Add(alarm);

            return tree;
        }

        /// <summary>
        /// Befores the write.
        /// </summary>
        /// <autogeneratedoc />
        protected virtual void BeforeWrite() { }

        /// <summary>
        /// Afters the write.
        /// </summary>
        /// <autogeneratedoc /> 
        protected virtual void AfterWrite() { }

        /// <summary>
        /// Called when /[write].
        /// </summary>
        /// <param name="tree">The tree.</param>
        /// <autogeneratedoc />
        protected virtual void OnWrite(AlarmSyntaxTree tree)
        {
            SetSyntaxTree(tree);
        }

        /// <summary>
        /// Writes the specified tree.
        /// </summary>
        /// <param name="tree">The tree.</param>
        /// <autogeneratedoc />
        public void Write(AlarmSyntaxTree tree)
        {
            this.BeforeWrite();
            this.OnWrite(tree);
            SetSyntaxTree(tree);
            this.AfterWrite();
        }
    }
}
